Module changes for auto ami update
spotinst/terraform-spotinst-ocean-aws-k8s pull request #26
Opened 2024-01-25 06:28 UTC by sobhanagit

_This is the default pull request template. You can customize it by adding a `pull_request_template.md` at the root of your repo or inside the `.github` folder._

# Jira Ticket

_Include a link to your Jira Ticket_
_Example: [JIRAISS-1234](https://spotinst.atlassian.net/browse/JIRAISS-1234)_

# Demo

_Please add a recording of the feature/bug fix in work. if you added new routes, the recording should show the request and response for each new/changed route_

# Checklist:
- [ ] I have filled relevant self assessment ([NodeJS](https://docs.google.com/forms/d/e/1FAIpQLSfl14u9AOBAmxVJ272tvO7XNuXE-EMvWaGcaRZalu1UAKB7RA/viewform), [Frontend](https://docs.google.com/forms/d/e/1FAIpQLSdiBPNKH81w_EkavihVL8Uwb0j7tP8PwJmLFYm2nCOQxz-1qw/viewform), [Backend](https://docs.google.com/forms/d/e/1FAIpQLSed_PsTJ5-XIWkFL6BSDE2AQRBVPmwc3PAmHZkUn-erzVI37Q/viewform?usp=sf_link))
- [ ] I have run ESlint on my changes and fixed all warnings and errors (**NodeJS & Frontend Services**)
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have validated all the requirements in the Jira task were answered
- [ ] I have all neccessary approvals for the design/mini design of this task
- [ ] I have approved the API changes and granular permission patterns (documentation subtask) (**For public services only**)

2024-01-25 13:04 UTC, chandra1-n commented on examples/basic/main.tf
> +  ami_id                         = "ami-02620bd547be274fb"
please remove the actual value

2024-01-25 13:05 UTC, chandra1-n commented on examples/basic/main.tf
> +  is_enabled                     = true
change the value to false

2024-01-25 13:05 UTC, chandra1-n commented on examples/basic/main.tf
> +    apply_roll                   = true
change the value to false

2024-01-25 13:06 UTC, chandra1-n commented on variables.tf
> +    batch_min_healthy_percentage = optional(number,50)
test keeping it as null instead of 50

2024-01-25 13:06 UTC, chandra1-n commented on variables.tf
> +    batch_min_healthy_percentage = optional(number,50)
test keeping it as null instead of 50

2024-01-25 13:06 UTC, chandra1-n requested changes
please fix the review comments

2024-01-25 13:14 UTC, chandra1-n commented on variables.tf
> +  description = "Customized List of conditioned roll params, it is valid only when conditioned_roll set to true"
this fix is merged today, please take latest

2024-02-03 13:26 UTC, anuragsharma-123 approved these changes

2024-02-03 13:27 UTC, chandra1-n approved these changes

2024-02-03 13:28 UTC, anuragsharma-123 approved these changes

2024-02-03 13:28 UTC, merged